facebookexperimental/doh-proxy

CHANGELOG.md
README.md
docs/index.md
dohproxy/protocol.py
dohproxy/stub.py
dohproxy/utils.py

As long as the HTTP2 connection seems to be up, we will send queries over the same connection.
This greatly help in improving latency. As an example, when setting up brand new connection on every queries, a DNS query would take 260ms, when re-using the same connection, it would only take 60ms.

Add support for multiple DNS queries over the same HTTP2 connection

---

CHANGELOG.md
README.md
dohproxy/httpproxy.py
dohproxy/proxy.py
dohproxy/utils.py
setup.py
test/test_utils.py

Add support for Proxying DOH over HTTP. This will allow putting doh-proxy behind a reverse proxy that may not support HTTP2 with backends.
Current assumption is that the reverse proxy and doh-proxy will run on the same host so I skipped SSL for now.

Http proxy

---

dohproxy/httpproxy.py
dohproxy/proxy.py
dohproxy/utils.py
test/test_utils.py

```The value may either be an explicit media type
(e.g. ct=application/dns-udpwireformat&body=...) or it may be empty.
An empty value indicates the default application/dns-udpwireformat
type (e.g. ct&body=...).```

[proxy] handle empty ct parameter

---

CHANGELOG.md
dohproxy/protocol.py

Fixes #17
:scheme should be set to `https`, not `h2`.
Tested with
```
PYTHONPATH=. python3 ./dohproxy/client.py  \
--domain dns.cloudflare.com \
--qname www.cloudflare.com \
--debug --post
```
as well as against dns.google.com implementation, nginx h2 and doh-proxy

[stub/client] set :scheme to HTTPS

---

CHANGELOG.md
dohproxy/httpproxy.py
dohproxy/proxy.py
dohproxy/utils.py

Fixes #16
This adds an `--upstream-port` option to the proxies implementation to
support using an alternative port to port 53.
It defaults to 53, so it does not need to be specificed in most common
cases.

[proxy] option to specific custome upstream port

---

CHANGELOG.md
dohproxy/__init__.py
dohproxy/utils.py
setup.py

This will allow maintaining setup.py version along with providing a way
for the tools to print their version number using --version.

Add central versioning

---

dohproxy/httpproxy.py
dohproxy/protocol.py
dohproxy/proxy.py
dohproxy/utils.py
test/test_utils.py

When unbound replies with a refused response, question is unset. This
caused the logging to throw an exception.
This change moves the log string generation to a separate function and
handles empty question section.
Fixes #21

[proxy] handle dns messages with empty question properly

---

README.md
dohproxy/constants.py
dohproxy/httpproxy.py
dohproxy/proxy.py
dohproxy/utils.py
test/test_utils.py

The main objective of this PR is to give support for TLS communication between a webserver (e.g. nginx) and the HTTPProxy module from doh-proxy.
Other changes:
For users:
- Now, for `doh-proxy`, the args `--certfile` and `--keyfile` are required;
In code:
- You need to explicitly enable `http2` to create a SSL Context for the proxies;
- Moved and renamed the function `ssl_context` (now `create_ssl_context` inside `utils`) and wrote tests for it;
- Since for `httpproxy` the TLS is optional, there is a new function to do the triage;

Adding httpproxy TLS support

---

dohproxy/client_protocol.py
dohproxy/httpproxy.py
dohproxy/utils.py
setup.py
test/test_httpproxy.py

This commit handles X-Forwarded-For header in doh-httpproxy using aiohttp middleware (dependency - aiohttp_remotes).
The client IP is set in the request, and carried along. Finally, the log is modified to include the client IP after successful DNS response.
I tried adding the trusted parameter (https://aiohttp-remotes.readthedocs.io/en/stable/api.html#trusted-hosts). The middleware is incompatible with sockets created by AF_INET6 (https://github.com/aio-libs/aiohttp-remotes/blob/master/aiohttp_remotes/x_forwarded.py#L94). The peername for AF_INET6 would return a 4-tuple; so the middleware would raise an exception (Too many values to unpack).

#25: Handled X-Forwarded-For header for httpproxy

---

README.md

Port 8080 can be opened with lower privileges so _sudo_ is not required.

Remove unnecessary use of sudo

---

dohproxy/httpproxy.py
dohproxy/proxy.py
dohproxy/server_protocol.py
test/test_httpproxy.py
test/test_protocol.py

Note: this PR is now in pre-review state. Before running a official review, there are a couple of issue are need to be understanding:
1. how to mock a lambda object 
2. error for "object MagicMock can't be used in 'await' expression"
This PR tries to fix the previous ignoring inputed logger issue mentioned here:
https://github.com/facebookexperimental/doh-proxy/issues/56
It did the follows:
1.  Finding all occurences of instanciations of DNSClient and pass the logger as part of the context.
2. Testing  to confirm that a mocked DNSClient is called with logger passed to it.
3. Creating DNSClient tests `test/test_protocol.py` where DNSClientProtocol{UDP,TCP} would be mocked and ensuring that DNSClient passes the logger to them.
4. Replacing logger.debug with logger.exception in …

fix loggerIgnore issue and add unit tests

---

dohproxy/server_protocol.py
test/test_protocol.py

Accommodate cancelled futures resulting from timeouts via explicit checking, and add unit test to validate fix and guard against regressions. #56

Handle connection timeouts resulting in cancelled futures

---

dohproxy/utils.py
test/test_knownservers.py
test/test_utils.py

* Removes references to `set_npn_protocols` function
* Fixes domain names for BlahDNS queries in test/test_knownservers.py
Output of `python3 setup.py test`:
```
$ python3 setup.py test
running pytest
Searching for unittest-data-provider
Best match: unittest-data-provider 1.0.1
Processing unittest_data_provider-1.0.1-py3.6.egg
Using /Users/jakalyan/doh-proxy/.eggs/unittest_data_provider-1.0.1-py3.6.egg
Searching for pytest-cov
Best match: pytest-cov 2.7.1
Processing pytest_cov-2.7.1-py3.6.egg
Using /Users/jakalyan/doh-proxy/.eggs/pytest_cov-2.7.1-py3.6.egg
Searching for pytest-aiohttp
Best match: pytest-aiohttp 0.3.0
Processing pytest_aiohttp-0.3.0-py3.6.egg
Using /Users/jakalyan/doh-proxy/.eggs/pytest_aiohttp-0.3.0-py3.6.egg
Searching for pytest
Best match: pytest 4.4.2
Processing …
```

Removes support for NPN in doh-proxy

---

dohproxy/server_protocol.py

Addresses https://github.com/facebookexperimental/doh-proxy/issues/66
UDP ports remain open if an exception occurs during the connection. The problem can be reproduced by setting up an upstream proxy on a port other than 52. For example:
1. `sudo PYTHONPATH=. ./dohproxy/proxy.py --upstream-resolver=::1   --certfile=./fullchain.pem   --keyfile=./privkey.pem --upstream-port=12345`
2. Send requests to it with `PYTHONPATH=. ./dohproxy/client.py --domain localhost --insecure`
3. Observe ports remaining open after every request in step 2 `netstat -ant |grep 12345`
This fix prevents this issue from happening by closing UDP ports when an exception is received.

Fix for hanging UDP ports

---

dohproxy/httpproxy.py

utils.dns_query_from_body() returns a dns.message.Message. There is no
need to decode the body twice.
Signed-off-by: Christian Heimes <cheimes@redhat.com>

Don't decode body twice

---

dohproxy/utils.py

- Display logger name to differentiate between us and modules
- Do not display date/time when stdout is not a TTY, for example when
running from systemd and logging to syslog

Logging updates

---

setup.cfg

Users with a ~/.config/flake8 may have more or less restrictive flake8
options.  Explicitly define here what we wish `setup.py flake8` to test.
(These options are flake8's defaults as of 3.7.9.)

Explicitly define flake8 defaults

---

dohproxy/client_protocol.py
dohproxy/proxy.py
dohproxy/server_protocol.py
dohproxy/stub.py
dohproxy/utils.py
test/test_utils.py

Add TCP listen support. Allow for --listen-address to be comma-separated.  Or if netifaces is installed, "all" for all detected v4/v6 addresses on all interfaces.
The DoH client is shared between all listeners (taking a little bit of work using a wrapper mutable dict).
(Sorry for the multiple force push spam.  I've got a handful of PRs inflight, and was trying to keep them as clean to merge as possible.  Originally the TCP and multiple addresses changes were separated, but I decided to combine them, as TCP itself is a separate "address" listen.)

doh-stub: Support TCP listen, multiple --listen-address (or "all")

---

dohproxy/httpproxy.py
dohproxy/proxy.py
dohproxy/server_protocol.py
dohproxy/utils.py
test/test_utils.py

In a nutshell, ECS is like X-Forwarded-For for DNS, and lets DNS
resolvers and proxies tell authoritative servers where the request
originated (down to a /24 v4 or /56 v6 network).  IMHO this should
be the default, but I've left it as an option.

Implement RFC 7871 EDNS Client Subnet (ECS)

---

dohproxy/client_protocol.py

Fixes #94
This header was previously overridden, because we only support `application/dns-message`, lets add it to the default headers

Add Accept header to queries

---

dohproxy/server_protocol.py

This fixes #99 
I repeated the same test with the exact setup as in the issue:
Server started as follows:
```
PYTHONPATH=. python3 dohproxy/httpproxy.py --trusted --upstream-resolver 192.168.2.10 --listen-address 127.0.0.1 --port 8000
```
Sample request: 
```
>curl http://127.0.0.1:8000/dns-query\?dns\=gCsBAAABAAAAAAAAB2V4YW1wbGUDY29tAAABAAE -I -w "%{time_total}" --max-time 30
HTTP/1.1 200 OK
Content-Type: application/dns-message
Content-Length: 0
Date: Thu, 11 Feb 2021 01:30:11 GMT
Server: Python/3.8 aiohttp/3.7.3
20.030092
```
Sample debug log message:
```
2021-02-10 17:25:59,159: doh-httpproxy/DEBUG: Timeout connecting to upstream resolver 192.168.2.10:53
```

Add TCP connect timeout
